language: shell
os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-7
before_script:
  - make 
script:
  - ./hello
notifications:
  email: false
after_success:
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: hello
  skip_cleanup: true
  draft: true
