language: shell
os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-7
before_script:
  - make 
script:
  - ./hello
notifications:
  email: false
after_success:
before_deploy:
  - mkdir hello-$TRAVIS_TAG
  - mv hello hello-$TRAVIS_TAG
  - tar cJvf hello-$TRAVIS_TAG.tar.xz hello-$TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: hello-$TRAVIS_TAG.tar.xz
  skip_cleanup: true
  on:
    branch: main
    tags: true
